hostnames:
  - node-01
  - node-02
  - node-03
  - node-04
  - node-05

vlans:
  - id: 100
    ips:
      - 192.168.100.10
      - 192.168.100.11
      - 192.168.100.12
      - 192.168.100.13
      - 192.168.100.14

  - id: 200
    ips:
      - 192.168.200.10
      - 192.168.200.11
      - 192.168.200.12
      - 192.168.200.13
      - 192.168.200.14

prefixLength: 24