hostnames:
  - r520-107
  - r520-108
  - sm106

vlans:
  - id: 100
    ips:
      - 192.168.100.10
      - 192.168.100.11
      - 192.168.100.12

  - id: 200
    ips:
      - 192.168.200.10
      - 192.168.200.11
      - 192.168.200.12

prefixLength: 24
